texto = input()
texto = texto.replace("zero","0")
texto = texto.replace("um","1")
texto = texto.replace("dois","2")
texto = texto.replace("três","3")
texto = texto.replace("quatro","4")
texto = texto.replace("cinco","5")
texto = texto.replace("seis","6")
texto = texto.replace("sete","7")
texto = texto.replace("oito","8")
texto = texto.replace("nove","9")
print(texto)
